version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    on-failure: ABORT
    commands: 
      - echo "INSTALANDO O NODE"
  
  pre_build:
    commands: 
      - npm i
      - echo "INSTALANDO AS DEPENDÊNCIAS"
  
  #build:
  #  commands:
  #    - npm run build
  #    - echo "FAZENDO BUILD"
      
  post_build:
    commands:
      - echo "RODOU O LINT"

cache:
  paths:
    - "/node_modules/**/*"
    - "/root/.npm/**/*"
