version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    on-failure: ABORT
    commands: 
      - echo "Instalando o node ATUALIZADO"
        
  pre_build:
    commands:
      - npm i 
      - echo "Instalou as dependências"
  
  build:
    commands:
      - npm run build
      - echo "Fez o build"

  post_build:
    commands:
      - echo "Executou após o build"

artifacts:
  files:
    - "**/*.js"
    - "**/*.html"
    - "**/*.css"
    - "**/*.ico"
  base-directory: dist/game
  discard-paths: yes

cache:
  paths:
    - "node_modules/**/*"
    #- "/root/.npm/**/*"
