version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    on-failure: ABORT
    commands: 
      - echo "Instalando o node"
    
  build:
    commands:
      - npm i 
      - echo "Instalou as dependências"
      
  post_build:
    commands:
      - echo "Rodou o lint"



